--BASE DEDATOS PELICULA

--CONSULTES SOBRE UNA TABLA--

--Activitat 1
SELECT DISTINCT cod_pais
FROM CS_actor
ORDER BY COD_PAIS;

--Activitat 2
SELECT cod_peli, titulo
FROM CS_PELICULA
WHERE ANYO < 1970 AND cod_lib IS NULL
ORDER BY TITULO;

--Activitat 3
SELECT cod_act, nombre
FROM CS_actor
WHERE nombre LIKE '%John%';

--Activitat 4
SELECT cod_peli, TITULO
FROM CS_PELICULA
WHERE DURACION >120 AND ANYO BETWEEN 1980 AND 1989;

--Activitat 5
SELECT COD_PELI, TITULO
FROM Cs_PELICULA
WHERE COD_LIB IS NOT NULL AND DIRECTOR LIKE '_% Pakula%';

--Activitat 6
SELECT COUNT(*)
FROM CS_PELICULA
WHERE DURACION >120 AND ANYO BETWEEN 1980 AND 1989;

--Activitat 7
SELECT COUNT(DISTINCT COD_PELI)
FROM CS_CLASIFICACION
WHERE COD_GEN IN('BB5','GG4','JH6');

--Activitat 8
SELECT MIN (ANYO)
FROM CS_libro;

--Activitat 9
SELECT AVG(DURACION)
FROM CS_PELICULA
WHERE ANYO = 1987;

--Activitat 10
SELECT SUM (DURACION)
FROM CS_PELICULA
WHERE DIRECTOR = 'Steven Spielberg';

--CONSULTES SOBRE VARIES TABLES--

--Activitat 11
SELECT P1.COD_PELI, P1.TITULO
FROM CS_PELICULA P1
WHERE P1.DIRECTOR IN
    (SELECT A1.NOMBRE
     FROM CS_ACTOR A1, CS_ACTUA A2
     WHERE P1.COD_PELI = A2.COD_PELI AND A2.COD_ACT = A1.COD_ACT)
ORDER BY P1.TITULO;

--Activitat 12
SELECT P1.COD_PELI, P1.TITULO
FROM CS_PELICULA P1, CS_GENERO G1, CS_CLASIFICACION C1
WHERE P1.COD_PELI = C1.COD_PELI AND C1.COD_GEN = G1.COD_GEN
AND G1.NOMBRE = 'Comedia'
ORDER BY TITULO;

--Activitat 13
SELECT P1.COD_PELI, P1.TITULO
FROM CS_PELICULA P1, CS_LIBRO L1
WHERE P1.COD_LIB = L1.COD_LIB AND L1.ANYO <1950
ORDER BY P1.TITULO;

--Activitat 14
SELECT DISTINCT PA.COD_PAIS, PA.NOMBRE
FROM CS_ACTUA AC,CS_ACTOR AC1, CS_PELICULA PE, CS_PAIS PA, CS_CLASIFICACION C1, CS_GENERO G1
WHERE PE.COD_PELI = C1.COD_PELI AND C1.COD_GEN = G1.COD_GEN AND G1.NOMBRE = 'Comedia'
AND PE.COD_PELI = AC.COD_PELI AND AC.COD_ACT = AC1.COD_ACT AND AC1.COD_PAIS = PA.COD_PAIS
ORDER BY PA.NOMBRE;

--Activitat 15 (REFER DE LA 11 A LA 14)
SELECT p.cod_peli, p.titulo
FROM cs_pelicula p
WHERE p.director IN (
    SELECT a.nombre
    FROM cs_actor a
    WHERE a.cod_act IN (
        SELECT x.cod_act
        FROM cs_actua x
        WHERE x.cod_peli = p.cod_peli
    )
) ORDER BY p.titulo;

SELECT p.cod_peli, p.titulo
FROM cs_pelicula p
WHERE p.cod_peli IN (
    SELECT c.cod_peli
    FROM cs_clasificacion c
    WHERE c.cod_gen IN (
        SELECT g.cod_gen
        FROM cs_genero g
        WHERE g.nombre = 'Comedia'
    )
) ORDER BY p.titulo;

SELECT DISTINCT p.cod_peli, p.titulo
FROM cs_pelicula p
WHERE p.cod_lib IN (
    SELECT cod_lib
    FROM cs_libro
    WHERE anyo < 1950
) ORDER BY p.titulo;

SELECT cod_pais, nombre
FROM cs_pais
WHERE cod_pais IN (
    SELECT cod_pais
    FROM cs_actor
    WHERE cod_act IN (
        SELECT cod_act
        FROM cs_actua
        WHERE cod_peli IN (
            SELECT cod_peli
            FROM cs_clasificacion
            WHERE cod_gen IN (
                SELECT cod_gen
                FROM cs_genero
                WHERE nombre = 'Comedia'
            )
        )
    )
) ORDER BY nombre;

--Activitat 16
SELECT A1.NOMBRE, A1.COD_ACT
FROM CS_ACTOR A1
WHERE A1.COD_ACT IN
    (SELECT AC.COD_ACT FROM CS_ACTUA AC
     WHERE AC.PAPEL = 'Principal')
AND EXTRACT (YEAR FROM A1.FECHA_NAC) <1950
ORDER BY A1.NOMBRE;

--Activitat 17
SELECT L1.COD_LIB, L1.TITULO,L1.AUTOR
FROM CS_LIBRO L1
WHERE L1.COD_LIB IN
    (SELECT P1.COD_LIB
     FROM CS_PELICULA P1
     WHERE P1.ANYO BETWEEN 1990 AND 1999)
ORDER BY L1.TITULO;

--Activitat 18
SELECT L1.COD_LIB, L1.TITULO, L1.AUTOR
FROM CS_LIBRO L1
WHERE L1.COD_LIB NOT IN
    (SELECT P1.COD_LIB
     FROM CS_PELICULA P1
     WHERE P1.COD_LIB IS NOT NULL);

--Activitat 19
SELECT DISTINCT G1.NOMBRE
FROM CS_GENERO G1,CS_PELICULA P1, CS_CLASIFICACION C1
WHERE P1.COD_PELI = C1.COD_PELI AND G1.COD_GEN = C1.COD_GEN AND P1.COD_PELI NOT IN
    (SELECT A1.COD_PELI
     FROM CS_ACTUA A1
     WHERE A1.COD_ACT IS NOT NULL)
ORDER BY G1.NOMBRE;

--ACTIVITAT 20
SELECT L1.TITULO
FROM CS_LIBRO L1
WHERE L1.COD_LIB IN
    (SELECT P1.COD_LIB
    FROM CS_PELICULA P1
    WHERE P1.COD_PELI NOT IN
        (SELECT ACT.COD_PELI
        FROM CS_ACTUA ACT
        WHERE ACT.COD_ACT NOT IN
            (SELECT AC.COD_ACT
             FROM CS_ACTOR AC
             WHERE AC.COD_PAIS NOT IN
                (SELECT PA.COD_PAIS
                 FROM CS_PAIS PA
                 WHERE PA.NOMBRE = 'USA'))))
ORDER BY L1.TITULO;

--ACTIVITAT 21
SELECT COUNT(PA.COD_PELI)
FROM CS_PELICULA PA
WHERE PA.COD_PELI IN (SELECT CL.COD_PELI
                     FROM CS_CLASIFICACION CL
                     WHERE CL.COD_GEN IN (SELECT GE.COD_GEN
                                         FROM CS_GENERO GE
                                         WHERE GE.NOMBRE = 'Comedia'))
     AND PA.COD_PELI IN (SELECT AC.COD_PELI
                         FROM CS_ACTUA AC
                         WHERE AC.COD_PELI = PA.COD_PELI AND AC.PAPEL = 'Secundario');

--Activitat 22
SELECT MIN(PE.ANYO)
FROM CS_PELICULA PE
WHERE PE.COD_PELI IN(SELECT ACT.COD_PELI
                     FROM CS_ACTUA ACT
                     WHERE ACT.COD_ACT IN(SELECT AC.COD_ACT
                                          FROM CS_ACTOR AC
                                          WHERE AC.NOMBRE = 'Jude Law'));

--Activitat 23
SELECT AC1.COD_ACT, AC1.NOMBRE
FROM CS_ACTOR AC1
WHERE AC1.FECHA_NAC <=ALL(SELECT AC2.FECHA_NAC
                          FROM CS_ACTOR AC2);

--Activitat 24
SELECT AC1.COD_ACT, AC1.NOMBRE, AC1.FECHA_NAC
FROM CS_ACTOR AC1
WHERE EXTRACT(YEAR FROM(AC1.FECHA_NAC))=1940
      AND AC1.FECHA_NAC <=ALL(SELECT AC2.FECHA_NAC
                              FROM CS_ACTOR AC2
                              WHERE EXTRACT(YEAR FROM(AC2.FECHA_NAC))=1940);

--Activitat 25
SELECT GE.NOMBRE
FROM CS_GENERO GE
WHERE GE.COD_GEN IN (SELECT CL.COD_GEN
                     FROM CS_CLASIFICACION CL
                     WHERE CL.COD_PELI IN (SELECT PE.COD_PELI
                                           FROM CS_PELICULA PE
                                           WHERE PE.DURACION >=ALL(SELECT PE2.DURACION
                                                                   FROM CS_PELICULA PE2)))
ORDER BY GE.NOMBRE;

--Activitat 26
SELECT L1.COD_LIB, L1.TITULO
FROM CS_LIBRO L1
WHERE L1.COD_LIB IN (SELECT PE.COD_LIB
                     FROM CS_PELICULA PE
                     WHERE PE.COD_PELI IN (SELECT ACT.COD_PELI
                                           FROM CS_ACTUA ACT
                                           WHERE ACT.COD_ACT IN (SELECT AC.COD_ACT
                                                                 FROM CS_ACTOR AC
                                                                 WHERE AC.COD_PAIS IN (SELECT PA.COD_PAIS
                                                                                       FROM CS_PAIS PA
                                                                                       WHERE PA.NOMBRE = 'Espa�a'))))
ORDER BY L1.TITULO;

--Activitat 27
SELECT PE.TITULO
FROM CS_PELICULA PE
WHERE PE.COD_PELI IN (SELECT CL.COD_PELI
                      FROM CS_CLASIFICACION CL
                      WHERE CL.COD_GEN IN (SELECT GE.COD_GEN
                                           FROM CS_GENERO GE))
     AND PE.ANYO<1950
ORDER BY PE.TITULO;

--Activitat 28
SELECT COUNT(*)
FROM CS_PELICULA PE
WHERE 4 >((SELECT COUNT(DISTINCT(AC.COD_ACT))
           FROM CS_ACTUA ACT, CS_ACTOR AC
           WHERE ACT.COD_PELI =PE.COD_PELI AND AC.COD_ACT = ACT.COD_ACT));

--Activitat 29
SELECT DISTINCT(PE.DIRECTOR)
FROM CS_PELICULA PE
WHERE  250 < (SELECT SUM(P2.DURACION) FROM CS_PELICULA P2 WHERE PE.DIRECTOR = P2.DIRECTOR);

--Activitat 30
SELECT DISTINCT(EXTRACT(YEAR FROM(AC.FECHA_NAC)))
FROM CS_ACTOR AC
WHERE 3 < (SELECT COUNT(*)
           FROM CS_ACTOR AC2
           WHERE EXTRACT(YEAR FROM(AC.FECHA_NAC)) = EXTRACT(YEAR FROM(AC2.FECHA_NAC)));

--Activitat 31
SELECT AC.COD_ACT, AC.NOMBRE
FROM CS_ACTOR AC
WHERE AC.FECHA_NAC=(SELECT MAX(AC2.FECHA_NAC)
                    FROM CS_ACTOR AC2
                    WHERE AC2.COD_ACT IN (SELECT ACT.COD_ACT
                                         FROM CS_PELICULA PE, CS_ACTUA ACT,CS_CLASIFICACION CL
                                         WHERE ACT.COD_PELI = PE.COD_PELI AND PE.COD_PELI = CL.COD_PELI AND CL.COD_GEN = 'DD8'));

--CONSULTES UNIVERSALMENT CUANTIFICADES--

--ACTIVITAT 32
SELECT PA.COD_PAIS, PA.NOMBRE
FROM CS_PAIS PA
WHERE EXISTS
    (SELECT *
     FROM CS_ACTOR AC
     WHERE EXTRACT(YEAR FROM AC.FECHA_NAC) NOT BETWEEN 1900 AND 2000
     AND AC.COD_PAIS <> PA.COD_PAIS
     )
     AND EXISTS
    (SELECT *
     FROM CS_ACTOR AC
     WHERE EXTRACT(YEAR FROM AC.FECHA_NAC) BETWEEN 1900 AND 2000
     AND AC.COD_PAIS = PA.COD_PAIS)
ORDER BY PA.NOMBRE;

--ACTIVITAT 33
SELECT AC.COD_ACT, AC.NOMBRE
FROM CS_ACTOR AC
WHERE NOT EXISTS
    (SELECT *
     FROM CS_ACTUA ACT
     WHERE AC.COD_ACT = ACT.COD_ACT
     AND  ACT.PAPEL <>'Secundario'
     AND ACT.COD_PELI IN (SELECT PE.COD_PELI FROM CS_PELICULA PE)
     )
    AND EXISTS
    (SELECT *
     FROM CS_ACTUA ACT
     WHERE AC.COD_ACT = ACT.COD_ACT
     AND ACT.COD_PELI IN (SELECT PE.COD_PELI FROM CS_PELICULA PE)
     AND  ACT.PAPEL ='Secundario')
ORDER BY AC.NOMBRE;

--ACTIVITAT 34 amb exist
SELECT AC.COD_ACT, AC.NOMBRE
FROM CS_ACTOR AC
WHERE EXISTS
    (SELECT * FROM CS_PELICULA P1, CS_ACTUA ACT WHERE P1.DIRECTOR = 'Guy Ritchie' AND P1.COD_PELI = ACT.COD_PELI AND ACT.COD_ACT = AC.COD_ACT)
AND EXISTS
    (SELECT * FROM CS_PELICULA P1 WHERE P1.DIRECTOR <> 'Guy Ritchie')
ORDER BY AC.NOMBRE;

--ACTIVITAT 34 contant
SELECT A1.NOMBRE
FROM CS_Actor A1
WHERE (SELECT COUNT(*)
       FROM CS_Pelicula P
       WHERE P.director = 'Guy Ritchie')
    =
      (SELECT COUNT(*)
       FROM CS_Pelicula P2, CS_Actua Ac
       WHERE P2.director = 'Guy Ritchie' AND Ac.cod_act = A1.cod_Act AND Ac.cod_peli = P2.cod_peli)
    AND
      (SELECT COUNT(*)
       FROM CS_Pelicula P1
       WHERE P1.director = 'Guy Ritchie' ) > 0
ORDER BY A1.NOMBRE;

--ACTIVITAT 35 amb exist
SELECT AC.COD_ACT, AC.NOMBRE
FROM CS_ACTOR AC
WHERE EXISTS
    (SELECT * FROM CS_PELICULA P1, CS_ACTUA ACT WHERE P1.DIRECTOR = 'John Steel' AND P1.COD_PELI = ACT.COD_PELI AND ACT.COD_ACT = AC.COD_ACT)
AND EXISTS
    (SELECT * FROM CS_PELICULA P1 WHERE P1.DIRECTOR <> 'John Steel')
ORDER BY AC.NOMBRE;

--ACTIVITAT 35 contant
SELECT A1.COD_ACT,A1.NOMBRE
FROM CS_Actor A1
WHERE (SELECT COUNT(*)
       FROM CS_Pelicula P
       WHERE P.director = 'John Steel')
    =
      (SELECT COUNT(*)
       FROM CS_Pelicula P2, CS_Actua Ac
       WHERE P2.director = 'John Steel' AND Ac.cod_act = A1.cod_Act AND Ac.cod_peli = P2.cod_peli)
    AND
      (SELECT COUNT(*)
       FROM CS_Pelicula P1
       WHERE P1.director = 'John Steel' ) > 0
ORDER BY A1.NOMBRE;

--ACTIVITAT 36
SELECT P.cod_PELI,P.titulo
FROM CS_Pelicula P, CS_Pais PA
WHERE P.duracion < 100
        AND (SELECT COUNT(*)
             FROM CS_Actua AC
             WHERE AC.cod_peli = P.cod_peli)
            =
            (SELECT COUNT(*)
             FROM CS_Actua AC, CS_Actor A
             WHERE AC.cod_peli = P.cod_peli AND
             A.cod_Act = AC.cod_act AND A.cod_pais = PA.cod_pais)
         AND (SELECT COUNT(*)
              FROM CS_Actua AC
              WHERE AC.cod_peli = P.cod_peli) > 0
ORDER BY P.COD_PELI;

--ACTIVITAT 37
SELECT PE.COD_PELI, PE.TITULO,PE.ANYO
FROM CS_PELICULA PE
WHERE(SELECT COUNT(*)
       FROM CS_ACTOR AC, CS_ACTUA ACT
       WHERE AC.COD_ACT = ACT.COD_ACT AND PE.COD_PELI = ACT.COD_PELI)
       =
       (SELECT COUNT(*)
       FROM CS_ACTOR AC, CS_ACTUA ACT
       WHERE AC.COD_ACT = ACT.COD_ACT AND PE.COD_PELI = ACT.COD_PELI AND EXTRACT(YEAR FROM (AC.FECHA_NAC))<1943)
       AND
       (SELECT COUNT(*)
       FROM CS_ACTOR AC, CS_ACTUA ACT
       WHERE AC.COD_ACT = ACT.COD_ACT AND PE.COD_PELI = ACT.COD_PELI) >0
ORDER BY PE.TITULO;

--ACTIVITAT 38
SELECT PA.COD_PAIS, PA.NOMBRE
FROM CS_PAIS PA
WHERE (SELECT COUNT(DISTINCT AC.COD_ACT)
       FROM CS_ACTUA ACT,CS_ACTOR AC
       WHERE AC.COD_PAIS = PA.COD_PAIS AND ACT.COD_ACT = AC.COD_ACT
       AND ACT.COD_PELI IN (SELECT PE.COD_PELI FROM CS_PELICULA PE WHERE PE.DURACION >120))
      =
       (SELECT COUNT(*)
        FROM  CS_ACTOR AC
        WHERE AC.COD_PAIS = PA.COD_PAIS)
      AND
        (SELECT COUNT(*)
        FROM  CS_ACTOR AC
        WHERE AC.COD_PAIS = PA.COD_PAIS)> 0
ORDER BY PA.NOMBRE;

--CONSULTES AGRUPADES--

--ACTIVITAT 39
SELECT L.COD_LIB, L.TITULO, COUNT(PE.COD_LIB)
FROM CS_LIBRO L, CS_PELICULA PE
WHERE L.COD_LIB = PE.COD_LIB
GROUP BY L.COD_LIB, L.TITULO
HAVING COUNT(PE.COD_LIB) > 1;

--ACTIVITAT 40
SELECT GE.COD_GEN, GE.NOMBRE, COUNT(CL.COD_GEN), ROUND(AVG(PE.DURACION))
FROM CS_GENERO GE, CS_PELICULA PE, CS_CLASIFICACION CL
WHERE CL.COD_GEN = GE.COD_GEN AND PE.COD_PELI = CL.COD_PELI
GROUP BY GE.COD_GEN, GE.NOMBRE
HAVING COUNT(CL.COD_GEN) >5
ORDER BY GE.NOMBRE;

--ACTIVITAT 41
SELECT PE.COD_PELI, PE.TITULO, COUNT(CL.COD_PELI)
FROM CS_PELICULA PE, CS_CLASIFICACION CL
WHERE PE.COD_PELI = CL.COD_PELI AND PE.ANYO >2000
GROUP BY PE.COD_PELI, PE.TITULO
ORDER BY TITULO;

--ACTIVITAT 42
SELECT PE.DIRECTOR
FROM CS_PELICULA PE
WHERE PE.DIRECTOR LIKE 'George%'
GROUP BY PE.DIRECTOR
HAVING COUNT(PE.COD_PELI)= 2;

--ACTIVITAT 43
SELECT PE.COD_PELI, PE.TITULO, COUNT(ACT.COD_ACT)
FROM CS_PELICULA PE, CS_ACTUA ACT, CS_CLASIFICACION CL
WHERE ACT.COD_PELI = PE.COD_PELI AND CL.COD_PELI = PE.COD_PELI
GROUP BY PE.COD_PELI, PE.TITULO
HAVING COUNT(ACT.COD_ACT) > 0 AND COUNT(DISTINCT CL.COD_GEN) = 1-- Distinct per que hi ha multiples actors
ORDER BY PE.TITULO;

--ACTIVITAT 44
SELECT PA.COD_PAIS, PA.NOMBRE, COUNT(DISTINCT ACT.COD_ACT)
FROM CS_PAIS PA, CS_ACTOR AC, CS_ACTUA ACT, CS_PELICULA PE
WHERE PA.COD_PAIS = AC.COD_PAIS AND ACT.COD_ACT = AC.COD_ACT AND PE.COD_PELI = ACT.COD_PELI AND PE.ANYO BETWEEN 1960 AND 1970
GROUP BY PA.COD_PAIS, PA.NOMBRE
HAVING COUNT(DISTINCT AC.COD_ACT) > 0
ORDER BY PA.NOMBRE;

--ACTIVITAT 45
SELECT GE.COD_GEN, GE.NOMBRE
FROM CS_GENERO GE, CS_CLASIFICACION CL
WHERE GE.COD_GEN = CL.COD_GEN
GROUP BY GE.COD_GEN, GE.NOMBRE
HAVING COUNT(DISTINCT CL.COD_PELI) >= ALL(SELECT COUNT(DISTINCT CL2.COD_PELI)
                                          FROM CS_CLASIFICACION CL2
                                          GROUP BY CL2.COD_GEN);

--ACTIVITAT 46
SELECT L.COD_LIB, L.TITULO, L.AUTOR
FROM CS_LIBRO L, CS_PELICULA PE
WHERE L.COD_LIB = PE.COD_LIB
GROUP BY L.COD_LIB, L.TITULO, L.AUTOR
HAVING COUNT(PE.COD_PELI) >= ALL(SELECT COUNT(PE2.COD_PELI)
                                FROM CS_PELICULA PE2
                                WHERE PE2.COD_LIB IS NOT NULL
                                GROUP BY PE2.COD_LIB);

-- Exercise 47
SELECT cod_pais, cs_pais.nombre
FROM cs_pais LEFT JOIN cs_actor USING (cod_pais)
WHERE cod_act IN (
    SELECT cod_act
    FROM cs_actua
    GROUP BY cod_act
    HAVING COUNT(DISTINCT cod_peli) = 2
) GROUP BY cod_pais, cs_pais.nombre
HAVING COUNT(cod_act) >= ALL (
    SELECT COUNT(cod_act)
    FROM cs_pais LEFT JOIN cs_actor USING (cod_pais)
    WHERE cod_act IN (
        SELECT cod_act
        FROM cs_actua
        GROUP BY cod_act
        HAVING COUNT(DISTINCT cod_peli) = 2
    ) GROUP BY cod_pais
);

-- Exercise 48
SELECT EXTRACT(YEAR FROM fecha_nac) A�O, COUNT(cod_act) NUM_ACTORES
FROM cs_actor
GROUP BY EXTRACT(YEAR FROM fecha_nac)
HAVING COUNT(cod_act) > 3;

-- Exercise 49 - redo 36
SELECT p.cod_peli, p.titulo
FROM cs_pelicula p, cs_actua x, cs_actor a
WHERE p.cod_peli = x.cod_peli
AND x.cod_act = a.cod_act
AND p.duracion < 100
GROUP BY p.cod_peli, p.titulo
HAVING COUNT(DISTINCT a.cod_pais) = 1;


-- QUERIES WITH DIFFERENT JOINS

-- Exercise 50
SELECT cod_pais, cs_pais.nombre, COUNT(cod_act)
FROM cs_pais LEFT JOIN cs_actor USING (cod_pais)
GROUP BY cod_pais, cs_pais.nombre
ORDER BY nombre;

-- Exercise 51
SELECT cod_lib, l.titulo, COUNT(cod_peli)
FROM cs_libro l LEFT JOIN cs_pelicula USING (cod_lib)
WHERE l.anyo > 1980
GROUP BY cod_lib, l.titulo;

-- Exercise 52
SELECT cod_pais, p.nombre, COUNT(DISTINCT a1.cod_act) ACT
FROM cs_pais p
  LEFT JOIN (cs_actor a1
    JOIN cs_actua a2
    ON papel = 'Secundario' -- if this is on where, all 0s get removed
    AND a1.cod_act=a2.cod_act)
  USING (cod_pais)
GROUP BY cod_pais, p.nombre
ORDER BY p.nombre;

-- Exercise 53
SELECT cod_peli, titulo, COUNT(DISTINCT cod_gen) GEN, COUNT(DISTINCT cod_act)
FROM (cs_pelicula LEFT JOIN cs_clasificacion USING (cod_peli))
    LEFT JOIN cs_actua USING (cod_peli)
WHERE duracion > 140
GROUP BY cod_peli, titulo
ORDER BY titulo;


-- QUERIES WITH SET OPERATIONS

-- Exercise 54
SELECT anyo
FROM cs_libro
WHERE anyo IS NOT NULL
AND anyo NOT LIKE '%9%'
  UNION
SELECT anyo
FROM cs_pelicula
WHERE anyo IS NOT NULL
AND anyo NOT LIKE '%9%';

-- OTHER QUERIES

-- Exercise 55
SELECT cod_gen, nombre
FROM cs_genero LEFT JOIN cs_clasificacion USING (cod_gen)
WHERE cod_peli IN (
    SELECT cod_peli
    FROM cs_pelicula
    WHERE duracion = (
        SELECT MAX(duracion)
        FROM cs_pelicula
    )
);

-- Exercise 56
SELECT cs_actor.cod_act, nombre, fecha_nac, COUNT(cod_peli) CUANTOS
FROM cs_actor
    LEFT JOIN cs_actua
    ON papel = 'Principal'
    AND cs_actor.cod_act = cs_actua.cod_act
WHERE cs_actor.cod_act IN (
    SELECT cod_act
    FROM cs_actor
    WHERE fecha_nac < '01/01/1948'
    AND cod_act IN (
        SELECT cod_act
        FROM cs_actua
        GROUP BY cod_act
        HAVING COUNT(DISTINCT cod_peli) >= 2
    )
) GROUP BY cs_actor.cod_act, nombre, fecha_nac
ORDER BY nombre;





--BASE DEDATOS MUSICA

--CONSULTAS SOBRE 1 SOLA RELACION

--ACTIVITAT 1
SELECT COUNT(*) DISCOS
FROM DISCO D;

--ACTIVITAT 2
SELECT G.NOMBRE
FROM  GRUPO G
WHERE G.PAIS != 'Espa�a';

--ACTIVITAT 3
SELECT CA.TITULO
FROM CANCION CA
WHERE CA.DURACION > 5;

--ACTIVITAT 4
SELECT DISTINCT(PE.FUNCION)
FROM GRUPO G, PERTENECE PE
WHERE G.COD = PE.COD
ORDER BY PE.FUNCION;

--ACTIVITAT 5
SELECT CL.NOMBRE, CL.NUM TAMA�O
FROM CLUB CL
ORDER BY CL.NUM;

--ACTIVITAT 6
SELECT CL.NOMBRE, CL.SEDE
FROM CLUB CL
WHERE CL.NUM > 500;

--CONSULTAS SOBRE VARIAS RELACIONES

--ACTIVITAT 7
SELECT CL.NOMBRE, CL.SEDE, G.NOMBRE
FROM CLUB CL, GRUPO G
WHERE CL.COD_GRU = G.COD AND G.PAIS = 'Espa�a';

--ACTIVITAT 8
SELECT A1.NOMBRE
FROM ARTISTA A1, PERTENECE PE, GRUPO G
WHERE A1.DNI = PE.DNI AND PE.COD = G.COD AND G.PAIS = 'Espa�a'
ORDER BY A1.NOMBRE;

--ACTIVITAT 9
SELECT DISTINCT(D.NOMBRE)--POT ESTAR EN VARIOS DISCO LA MATEIXA CAN��
FROM DISCO D, ESTA E1, CANCION CA
WHERE D.COD = E1.COD AND E1.CAN = CA.COD AND CA.DURACION > 5;

--ACTIVITAT 10
SELECT CA.TITULO
FROM DISCO D, ESTA E1, CANCION CA
WHERE D.COD = E1.COD AND E1.CAN = CA.COD AND CA.TITULO = D.NOMBRE;

--ACTIVITAT 11
SELECT CO.NOMBRE, CO.DIR
FROM DISCO D, COMPANYIA CO
WHERE CO.COD = D.COD_COMP AND D.NOMBRE LIKE 'A%';

--ACTIVITAT 12
SELECT DISTINCT P1.DNI
FROM PERTENECE P1, PERTENECE P2
WHERE P1.DNI = P2.DNI AND P1.COD <>P2.COD;

--CONSULTAS CON SUBCONSULTAS

--ACTIVITAT 13
SELECT D.NOMBRE
FROM DISCO D
WHERE D.COD_GRU IN (SELECT G.COD
                    FROM GRUPO G
                    WHERE G.FECHA = (SELECT MIN(G1.FECHA)
                                     FROM GRUPO G1));

--ACTIVITAT 14
SELECT D.NOMBRE
FROM DISCO D
WHERE D.COD_GRU IN (SELECT G.COD
                    FROM GRUPO G
                    WHERE G.COD IN(SELECT CL.COD_GRU
                                   FROM CLUB CL
                                   WHERE NUM > 5000));

--ACTIVITAT 15
SELECT CL.NOMBRE, CL.NUM
FROM CLUB CL
WHERE CL.NUM = (SELECT MAX(CL1.NUM)
                FROM CLUB CL1);

--ACTIVITAT 16
SELECT CA.TITULO, CA.DURACION
FROM CANCION CA
WHERE CA.DURACION = (SELECT MAX(CA1.DURACION)
                     FROM CANCION CA1);

--CONSULTAS DE CUANTIFICACI�N UNIVERSAL

--ACTIVITAT 17
SELECT CO.NOMBRE
FROM COMPANYIA CO
WHERE (SELECT COUNT(*)
       FROM DISCO D, GRUPO G
       WHERE D.COD_GRU = G.COD AND D.COD_COMP = CO.COD AND G.PAIS != 'Espa�a')
       =
       (SELECT COUNT(*)
        FROM DISCO D, GRUPO G
        WHERE D.COD_GRU = G.COD AND D.COD_COMP = CO.COD);
       --AND
       --(SELECT COUNT(*)
        --FROM DISCO D, GRUPO G
        --WHERE D.COD_GRU = G.COD AND D.COD_COMP = CO.COD) > 0; COM NO HAN DE TREBALLAR EL NULS TAMBE VALEN PERQUE NO HAN TREBALLAT

--ACTIVITAT 18
SELECT CO.NOMBRE
FROM COMPANYIA CO
WHERE (SELECT COUNT(*)
       FROM DISCO D, GRUPO G
       WHERE D.COD_GRU = G.COD AND D.COD_COMP = CO.COD AND G.PAIS = 'Espa�a')
       =
       (SELECT COUNT(*)
        FROM DISCO D, GRUPO G
        WHERE D.COD_GRU = G.COD AND D.COD_COMP = CO.COD)
      AND
       (SELECT COUNT(*)
        FROM DISCO D, GRUPO G
        WHERE D.COD_GRU = G.COD AND D.COD_COMP = CO.COD) > 0;

--ACTIVITAT 19
SELECT CO.NOMBRE, CO.DIR
FROM COMPANYIA CO
WHERE (SELECT COUNT(*)
       FROM DISCO D
       WHERE CO.COD = D.COD_COMP AND D.COD_GRU = ALL(SELECT G.COD
                                                     FROM GRUPO G
                                                     WHERE G.COD = D.COD_GRU))
    = (SELECT COUNT(*)
       FROM DISCO D
       WHERE CO.COD = D.COD_COMP)
    AND (SELECT COUNT(*)
            FROM DISCO D
            WHERE CO.COD = D.COD_COMP)>0
ORDER BY CO.NOMBRE;

--ACTIVITAT 20
SELECT G.NOMBRE, SUM(CL.NUM)
FROM GRUPO G, CLUB CL
WHERE G.COD = CL.COD_GRU AND G.PAIS = 'Espa�a'
GROUP BY G.NOMBRE;

--ACTIVITAT 21
SELECT G.NOMBRE, COUNT(DISTINCT PE.DNI)
FROM GRUPO G, PERTENECE PE
WHERE G.COD = PE.COD
GROUP BY G.NOMBRE
HAVING 2 < COUNT(DISTINCT PE.DNI);

--ACTIVITAT 22
SELECT G.NOMBRE, COUNT(D.COD)
FROM GRUPO G, DISCO D
WHERE G.COD = D.COD_GRU
GROUP BY G.NOMBRE;

--ACTIVITAT 23
SELECT CO.NOMBRE, COUNT(E.CAN), CO.DIR
FROM COMPANYIA CO LEFT JOIN (ESTA E NATURAL JOIN DISCO D) ON CO.COD = D.COD_COMP
GROUP BY CO.NOMBRE, CO.DIR
ORDER BY CO.NOMBRE;

--23 MAL
SELECT CO.NOMBRE, COUNT(E.CAN), CO.DIR
FROM COMPANYIA CO, DISCO D, ESTA E
WHERE CO.COD = D.COD_COMP AND D.COD = E.COD
GROUP BY CO.NOMBRE, CO.DIR
ORDER BY CO.NOMBRE;

--CONSULTAS SOBRE UNA TABLA
--ACTIVITAT 1
SELECT DISTINCT AC.COD_PAIS
FROM CS_ACTOR AC;

--ACTIVITAT 2
SELECT PE.COD_PELI, PE.TITULO
FROM CS_PELICULA PE
WHERE PE.ANYO < 1970 AND PE.COD_LIB IS NULL;

--ACTIVITAT 3
SELECT AC.COD_ACT, AC.NOMBRE
FROM CS_ACTOR AC
WHERE AC.NOMBRE LIKE '%John%';

--ACTIVITAT 4
SELECT PE.COD_PELI, PE.TITULO
FROM CS_PELICULA PE
WHERE PE.DURACION > 120 AND PE.ANYO BETWEEN 1980 AND 1989;

--ACTIVITAT 5
SELECT PE.COD_PELI, PE.TITULO
FROM CS_PELICULA PE
WHERE PE.COD_LIB IS NOT NULL AND PE.DIRECTOR LIKE '%Pakula';

--ACTIVITAT 6
SELECT COUNT(*) Peliculas
FROM CS_PELICULA PE
WHERE PE.DURACION > 120 AND PE.ANYO BETWEEN 1980 AND 1989;

--ACTIVITAT 7
SELECT COUNT(DISTINCT COD_PELI)
FROM CS_CLASIFICACION
WHERE COD_GEN IN('BB5','GG4','JH6');

--ACTIVITAT 8
SELECT MIN(L.ANYO)
FROM CS_LIBRO L;

--ACTIVITAT 9
SELECT AVG(PE.DURACION)
FROM CS_PELICULA PE
WHERE PE.ANYO = 1987;

--ACTIVITAT 10
SELECT SUM(PE.DURACION)
FROM CS_PELICULA PE
WHERE PE.DIRECTOR = 'Steven Spielberg';

--CONSULTAS SOBRE VARIAS TABLAS
--ACTIVITAT 11
SELECT PE.COD_PELI, PE.TITULO
FROM CS_PELICULA PE, CS_ACTUA ACT, CS_ACTOR AC
WHERE PE.COD_PELI = ACT.COD_PELI AND ACT.COD_ACT = AC.COD_ACT AND AC.NOMBRE = PE.DIRECTOR;

--ACTIVITAT 12
SELECT PE.COD_PELI,PE.TITULO
FROM CS_PELICULA PE, CS_CLASIFICACION CL, CS_GENERO G
WHERE PE.COD_PELI = CL.COD_PELI AND CL.COD_GEN = G.COD_GEN AND G.NOMBRE = 'Comedia'
ORDER BY PE.TITULO;

--ACTIVITAT 13
SELECT PE.COD_PELI, PE.TITULO
FROM CS_PELICULA PE, CS_LIBRO L
WHERE PE.COD_LIB=L.COD_LIB AND L.ANYO<1950
ORDER BY PE.TITULO;

--ACTIVITAT 14
SELECT DISTINCT PA.COD_PAIS, PA.NOMBRE
FROM CS_PAIS PA, CS_ACTOR AC, CS_ACTUA ACT, CS_PELICULA PE, CS_GENERO G, CS_CLASIFICACION CL
WHERE PA.COD_PAIS = AC.COD_PAIS AND AC.COD_ACT = ACT.COD_ACT AND ACT.COD_PELI = PE.COD_PELI AND PE.COD_PELI = CL.COD_PELI AND CL.COD_GEN = G.COD_GEN AND G.NOMBRE = 'Comedia'
ORDER BY PA.NOMBRE;

--CONSULTAS CON SUBCONSULTAS
--ACTIVITAT 15
--11 BIS
SELECT PE.COD_PELI, PE.TITULO
FROM CS_PELICULA PE
WHERE PE.COD_PELI IN(SELECT ACT.COD_PELI
                     FROM CS_ACTUA ACT
                     WHERE ACT.COD_ACT IN (SELECT AC.COD_ACT
                                           FROM CS_ACTOR AC
                                           WHERE AC.NOMBRE = PE.DIRECTOR));
--12 BIS
SELECT PE.COD_PELI,PE.TITULO
FROM CS_PELICULA PE
WHERE PE.COD_PELI IN(SELECT CL.COD_PELI
                     FROM CS_CLASIFICACION CL
                     WHERE CL.COD_GEN IN(SELECT G.COD_GEN
                                         FROM CS_GENERO G
                                         WHERE G.NOMBRE = 'Comedia'))
ORDER BY PE.TITULO;
--13 BIS
SELECT PE.COD_PELI, PE.TITULO
FROM CS_PELICULA Pe
WHERE PE.COD_LIB IN (SELECT L.COD_LIB
                     FROM CS_LIBRO L
                     WHERE L.ANYO<1950)
ORDER BY PE.TITULO;
--14 BIS
SELECT DISTINCT PA.COD_PAIS, PA.NOMBRE
FROM CS_PAIS PA
WHERE PA.COD_PAIS IN (SELECT AC.COD_PAIS
                      FROM CS_ACTOR AC
                      WHERE AC.COD_ACT IN (SELECT ACT.COD_ACT
                                           FROM CS_ACTUA ACT
                                           WHERE ACT.COD_PELI IN(SELECT PE.COD_PELI
                                                                 FROM CS_PELICULA PE
                                                                 WHERE PE.COD_PELI IN(SELECT CL.COD_PELI
                                                                                      FROM CS_CLASIFICACION CL
                                                                                      WHERE CL.COD_GEN IN (SELECT G.COD_GEN
                                                                                                           FROM CS_GENERO G
                                                                                                           WHERE G.NOMBRE = 'Comedia')))))
ORDER BY PA.NOMBRE;

--ACTIVITAT 16
SELECT AC.COD_ACT, AC.NOMBRE
FROM CS_ACTOR AC
WHERE AC.COD_ACT IN(SELECT ACT.COD_ACT
                    FROM CS_ACTUA ACT
                    WHERE ACT.PAPEL = 'Principal')
    AND AC.COD_ACT IN (SELECT AC1.COD_ACT
                       FROM CS_ACTOR AC1
                       WHERE EXTRACT(YEAR FROM(AC1.FECHA_NAC)) < 1950)
ORDER BY AC.NOMBRE;

--ACTIVITAT 17
SELECT L.COD_LIB, L.TITULO, L.AUTOR
FROM CS_LIBRO L
WHERE L.COD_LIB IN(SELECT PE.COD_LIB
                   FROM CS_PELICULA PE
                   WHERE PE.ANYO BETWEEN 1990 AND 1999)
ORDER BY L.TITULO;

--ACTIVITAT 18
SELECT L.COD_LIB, L.TITULO, L.AUTOR
FROM CS_LIBRO L
WHERE L.COD_LIB NOT IN (SELECT PE.COD_LIB
                        FROM CS_PELICULA PE
                        WHERE PE.COD_LIB IS NOT NULL);

--ACTIVITAT 19
SELECT G.NOMBRE
FROM CS_GENERO G
WHERE G.COD_GEN IN (SELECT CL.COD_GEN
                    FROM CS_CLASIFICACION CL
                    WHERE CL.COD_PELI IN(SELECT PE.COD_PELI
                                         FROM CS_PELICULA PE
                                         WHERE PE.COD_PELI NOT IN(SELECT A1.COD_PELI
                                                                 FROM CS_ACTUA A1
                                                                 WHERE A1.COD_ACT IS NOT NULL)))
ORDER BY G.NOMBRE;

--CONSULTAS GENERALES
--ACTIVITAT 32
SELECT DISTINCT PA.COD_PAIS, PA.NOMBRE
FROM CS_PAIS PA
WHERE (SELECT COUNT(*)
       FROM CS_ACTOR AC
       WHERE AC.COD_PAIS = PA.COD_PAIS AND EXTRACT(YEAR FROM(AC.FECHA_NAC)) > 1899)
       =
       (SELECT COUNT(*)
        FROM CS_ACTOR AC
        WHERE AC.COD_PAIS = PA.COD_PAIS)
      AND
       (SELECT COUNT(*)
        FROM CS_ACTOR AC
        WHERE AC.COD_PAIS = PA.COD_PAIS) > 0
ORDER BY PA.NOMBRE;

--ACTIVITAT 33
SELECT AC.COD_ACT, AC.NOMBRE
FROM CS_ACTOR AC
WHERE (SELECT COUNT(*)
       FROM CS_ACTUA ACT
       WHERE ACT.PAPEL = 'Secundario' AND ACT.COD_ACT = AC.COD_ACT)
       =
       (SELECT COUNT(*)
        FROM CS_ACTUA ACT
        WHERE ACT.COD_ACT = AC.COD_ACT)
      AND
        (SELECT COUNT(*)
        FROM CS_ACTUA ACT
        WHERE ACT.COD_ACT = AC.COD_ACT) > 0
ORDER BY AC.NOMBRE;

--ACTIVITAT 34
SELECT AC.COD_ACT, AC.NOMBRE
FROM CS_ACTOR AC
WHERE (SELECT COUNT(*)
       FROM CS_ACTUA ACT, CS_PELICULA PE
       WHERE AC.COD_ACT = ACT.COD_ACT AND ACT.COD_PELI = PE.COD_PELI AND PE.DIRECTOR = 'Guy Ritchie')
       =
       (SELECT COUNT(*)
        FROM CS_PELICULA PE
        WHERE PE.DIRECTOR = 'Guy Ritchie')
       AND
        (SELECT COUNT(*)
        FROM CS_PELICULA PE
        WHERE PE.DIRECTOR = 'Guy Ritchie') > 0;

--ACTIVITAT 35
SELECT AC.COD_ACT, AC.NOMBRE
FROM CS_ACTOR AC
WHERE (SELECT COUNT(*)
       FROM CS_ACTUA ACT, CS_PELICULA PE
       WHERE AC.COD_ACT = ACT.COD_ACT AND ACT.COD_PELI = PE.COD_PELI AND PE.DIRECTOR = 'John Steel')
       =
       (SELECT COUNT(*)
        FROM CS_PELICULA PE
        WHERE PE.DIRECTOR = 'John Steel')
       AND
        (SELECT COUNT(*)
        FROM CS_PELICULA PE
        WHERE PE.DIRECTOR = 'John Steel') > 0;

--ACTIVITAT 36
SELECT DISTINCT PE.COD_PELI, PE.TITULO
FROM CS_PELICULA PE, CS_PAIS PA
WHERE PE.DURACION < 100 AND
         (SELECT COUNT(DISTINCT AC.COD_ACT)
          FROM CS_ACTOR AC, CS_ACTUA ACT
          WHERE AC.COD_ACT = ACT.COD_ACT AND ACT.COD_PELI = PE.COD_PELI AND PA.COD_PAIS = AC.COD_PAIS)
         =
         (SELECT COUNT(DISTINCT AC.COD_ACT)
          FROM CS_ACTOR AC, CS_ACTUA ACT
          WHERE AC.COD_ACT = ACT.COD_ACT AND ACT.COD_PELI = PE.COD_PELI)
        AND
          (SELECT COUNT(DISTINCT AC.COD_ACT)
          FROM CS_ACTOR AC, CS_ACTUA ACT
          WHERE AC.COD_ACT = ACT.COD_ACT AND ACT.COD_PELI = PE.COD_PELI) > 0
ORDER BY PE.COD_PELI;

--ACTIVITAT 37
SELECT PE.COD_PELI, PE.TITULO, PE.ANYO
FROM CS_PELICULA PE
WHERE (SELECT COUNT(*)
       FROM CS_ACTUA ACT, CS_ACTOR AC
       WHERE PE.COD_PELI = ACT.COD_PELI AND AC.COD_ACT = ACT.COD_ACT)
       =
       (SELECT COUNT(*)
       FROM CS_ACTUA ACT, CS_ACTOR AC
       WHERE PE.COD_PELI = ACT.COD_PELI AND AC.COD_ACT = ACT.COD_ACT AND EXTRACT(YEAR FROM(AC.FECHA_NAC)) < 1943)
       AND
       (SELECT COUNT(*)
       FROM CS_ACTUA ACT, CS_ACTOR AC
       WHERE PE.COD_PELI = ACT.COD_PELI AND AC.COD_ACT = ACT.COD_ACT) > 0
ORDER BY PE.TITULO;

--ACTIVITAT 38
SELECT PA.COD_PAIS, PA.NOMBRE
FROM CS_PAIS PA
WHERE  (SELECT COUNT(*)
        FROM  CS_ACTOR AC
        WHERE AC.COD_PAIS = PA.COD_PAIS)
    =
      (SELECT COUNT(DISTINCT AC.COD_ACT)
       FROM CS_ACTOR AC, CS_ACTUA ACT,CS_PELICULA PE
       WHERE PA.COD_PAIS = AC.COD_PAIS AND AC.COD_ACT = ACT.COD_ACT AND PE.COD_PELI = ACT.COD_PELI AND PE.DURACION > 120)
    AND
       (SELECT COUNT(*)
        FROM  CS_ACTOR AC
        WHERE AC.COD_PAIS = PA.COD_PAIS) > 0
ORDER BY PA.NOMBRE;

--CONSULTAS AGRUPADAS
--ACTIVITAT 39
SELECT L.COD_LIB,L.TITULO, COUNT(PE.COD_PELI)
FROM CS_LIBRO L, CS_PELICULA PE
WHERE L.COD_LIB = PE.COD_LIB
GROUP BY L.COD_LIB, L.TITULO
HAVING COUNT(PE.COD_PELI)>1;

--ACTIVITAT 40
SELECT G.COD_GEN, G.NOMBRE, COUNT(CL.COD_PELI), ROUND(AVG(PE.DURACION))
FROM CS_GENERO G, CS_CLASIFICACION CL, CS_PELICULA PE
WHERE CL.COD_GEN = G.COD_GEN AND CL.COD_PELI = PE.COD_PELI
GROUP BY G.COD_GEN, G.NOMBRE
HAVING COUNT(CL.COD_PELI) > 5
ORDER BY G.NOMBRE;

--ACTIVITAT 41

--EXAMEN 1
SELECT TITULO, ANYO
FROM CS_PELICULA
WHERE COD_LIB IS NULL AND COD_PELI NOT IN (SELECT ACT.COD_PELI
                                           FROM CS_ACTUA ACT
                                           WHERE ACT.COD_ACT IN (SELECT COD_ACT FROM CS_ACTOR WHERE COD_PAIS = 'Italia'));
 --MAL
SELECT TITULO, ANYO
FROM CS_PELICULA
WHERE COD_LIB NOT IN (SELECT COD_LIB FROM CS_LIBRO) AND COD_PELI NOT IN (SELECT ACT.COD_PELI
                                           FROM CS_ACTUA ACT
                                           WHERE ACT.COD_ACT IN (SELECT COD_ACT FROM CS_ACTOR WHERE COD_PAIS = 'Italia'));
SELECT PE.TITULO,PE.ANYO, COUNT(DISTINCT ACT.COD_ACT)
FROM CS_PELICULA PE, CS_ACTUA ACT
WHERE PE.COD_PELI = ACT.COD_PELI
GROUP BY PE.TITULO, PE.ANYO, PE.COD_PELI
HAVING COUNT(ACT.COD_ACT)>2;

SELECT GE.NOMBRE
FROM CS_GENERO GE
WHERE (SELECT COUNT( P.COD_PELI)
       FROM CS_PELICULA P, CS_CLASIFICACION CLA
       WHERE GE.COD_GEN = CLA.COD_GEN AND CLA.COD_PELI = P.COD_PELI)
       =
       (SELECT COUNT(P.COD_PELI)
       FROM CS_PELICULA P, CS_CLASIFICACION CLA
       WHERE GE.COD_GEN = CLA.COD_GEN AND CLA.COD_PELI = P.COD_PELI AND P.COD_LIB IS NOT NULL)
       AND (SELECT COUNT(P.COD_PELI)
       FROM CS_PELICULA P, CS_CLASIFICACION CLA
       WHERE GE.COD_GEN = CLA.COD_GEN AND CLA.COD_PELI = P.COD_PELI) > 0;

SELECT GE.NOMBRE
FROM CS_GENERO GE
WHERE NOT EXISTS (SELECT (PE.COD_PELI)
                  FROM CS_PELICULA PE, CS_CLASIFICACION CLA
                  WHERE PE.COD_PELI = CLA.COD_PELI AND CLA.COD_GEN = GE.COD_GEN AND PE.COD_LIB IS NULL)
     AND EXISTS (SELECT (PE.COD_PELI)
                  FROM CS_PELICULA PE, CS_CLASIFICACION CLA
                  WHERE PE.COD_PELI = CLA.COD_PELI AND CLA.COD_GEN = GE.COD_GEN);

--ACTIVITAT 40
SELECT GE.COD_GEN, GE.NOMBRE, COUNT(CL.COD_GEN), ROUND(AVG(PE.DURACION))
FROM CS_GENERO GE, CS_PELICULA PE, CS_CLASIFICACION CL
WHERE CL.COD_GEN = GE.COD_GEN AND PE.COD_PELI = CL.COD_PELI
GROUP BY GE.COD_GEN, GE.NOMBRE
HAVING COUNT(CL.COD_GEN) >5
ORDER BY GE.NOMBRE;

--ACTIVITAT 41
SELECT PE.COD_PELI, PE.TITULO, COUNT(CL.COD_PELI)
FROM CS_PELICULA PE, CS_CLASIFICACION CL
WHERE PE.COD_PELI = CL.COD_PELI AND PE.ANYO >2000
GROUP BY PE.COD_PELI, PE.TITULO
ORDER BY TITULO;

--ACTIVITAT 42
SELECT PE.DIRECTOR
FROM CS_PELICULA PE
WHERE PE.DIRECTOR LIKE 'George%'
GROUP BY PE.DIRECTOR
HAVING COUNT(PE.COD_PELI)= 2;

--ACTIVITAT 43
SELECT PE.COD_PELI, PE.TITULO, COUNT(ACT.COD_ACT)
FROM CS_PELICULA PE, CS_ACTUA ACT, CS_CLASIFICACION CL
WHERE ACT.COD_PELI = PE.COD_PELI AND CL.COD_PELI = PE.COD_PELI
GROUP BY PE.COD_PELI, PE.TITULO
HAVING COUNT(ACT.COD_ACT) > 0 AND COUNT(DISTINCT CL.COD_GEN) = 1-- Distinct per que hi ha multiples actors
ORDER BY PE.TITULO;

--ACTIVITAT 44
SELECT PA.COD_PAIS, PA.NOMBRE, COUNT(DISTINCT ACT.COD_ACT)
FROM CS_PAIS PA, CS_ACTOR AC, CS_ACTUA ACT, CS_PELICULA PE
WHERE PA.COD_PAIS = AC.COD_PAIS AND ACT.COD_ACT = AC.COD_ACT AND PE.COD_PELI = ACT.COD_PELI AND PE.ANYO BETWEEN 1960 AND 1970
GROUP BY PA.COD_PAIS, PA.NOMBRE
HAVING COUNT(DISTINCT AC.COD_ACT) > 0
ORDER BY PA.NOMBRE;

--ACTIVITAT 45
SELECT GE.COD_GEN, GE.NOMBRE
FROM CS_GENERO GE, CS_CLASIFICACION CL
WHERE GE.COD_GEN = CL.COD_GEN
GROUP BY GE.COD_GEN, GE.NOMBRE
HAVING COUNT(DISTINCT CL.COD_PELI) >= ALL(SELECT COUNT(DISTINCT CL2.COD_PELI)
                                          FROM CS_CLASIFICACION CL2
                                          GROUP BY CL2.COD_GEN);

--ACTIVITAT 46
SELECT L.COD_LIB, L.TITULO, L.AUTOR
FROM CS_LIBRO L, CS_PELICULA PE
WHERE L.COD_LIB = PE.COD_LIB
GROUP BY L.COD_LIB, L.TITULO, L.AUTOR
HAVING COUNT(PE.COD_PELI) >= ALL(SELECT COUNT(PE2.COD_PELI)
                                FROM CS_PELICULA PE2
                                WHERE PE2.COD_LIB IS NOT NULL
                                GROUP BY PE2.COD_LIB);

-- Exercise 47
SELECT cod_pais, cs_pais.nombre
FROM cs_pais LEFT JOIN cs_actor USING (cod_pais)
WHERE cod_act IN (
    SELECT cod_act
    FROM cs_actua
    GROUP BY cod_act
    HAVING COUNT(DISTINCT cod_peli) = 2
) GROUP BY cod_pais, cs_pais.nombre
HAVING COUNT(cod_act) >= ALL (
    SELECT COUNT(cod_act)
    FROM cs_pais LEFT JOIN cs_actor USING (cod_pais)
    WHERE cod_act IN (
        SELECT cod_act
        FROM cs_actua
        GROUP BY cod_act
        HAVING COUNT(DISTINCT cod_peli) = 2
    ) GROUP BY cod_pais
);

-- Exercise 48
SELECT EXTRACT(YEAR FROM fecha_nac) AÑO, COUNT(cod_act) NUM_ACTORES
FROM cs_actor
GROUP BY EXTRACT(YEAR FROM fecha_nac)
HAVING COUNT(cod_act) > 3;

-- Exercise 49 - redo 36
SELECT p.cod_peli, p.titulo
FROM cs_pelicula p, cs_actua x, cs_actor a
WHERE p.cod_peli = x.cod_peli
AND x.cod_act = a.cod_act
AND p.duracion < 100
GROUP BY p.cod_peli, p.titulo
HAVING COUNT(DISTINCT a.cod_pais) = 1;


-- QUERIES WITH DIFFERENT JOINS

-- Exercise 50
SELECT pa.cod_pais, pa.nombre, COUNT(ac.cod_act)
FROM cs_pais pa LEFT JOIN cs_actor ac USING (cod_pais)
GROUP BY pa.cod_pais, pa.nombre
ORDER BY pa.nombre;

-- Exercise 51
SELECT cod_lib, l.titulo, COUNT(cod_peli)
FROM cs_libro l LEFT JOIN cs_pelicula USING (cod_lib)
WHERE l.anyo > 1980
GROUP BY cod_lib, l.titulo;

-- Exercise 52
SELECT cod_pais, p.nombre, COUNT(DISTINCT a1.cod_act) ACT
FROM cs_pais p
  LEFT JOIN (cs_actor a1
    JOIN cs_actua a2
    ON papel = 'Secundario' -- if this is on where, all 0s get removed
    AND a1.cod_act=a2.cod_act)
  USING (cod_pais)
GROUP BY cod_pais, p.nombre
ORDER BY p.nombre;

-- Exercise 53
SELECT cod_peli, titulo, COUNT(DISTINCT cod_gen) GEN, COUNT(DISTINCT cod_act)
FROM (cs_pelicula LEFT JOIN cs_clasificacion USING (cod_peli))
    LEFT JOIN cs_actua USING (cod_peli)
WHERE duracion > 140
GROUP BY cod_peli, titulo
ORDER BY titulo;


-- QUERIES WITH SET OPERATIONS

-- Exercise 54
SELECT anyo
FROM cs_libro
WHERE anyo IS NOT NULL
AND anyo NOT LIKE '%9%'
  UNION
SELECT anyo
FROM cs_pelicula
WHERE anyo IS NOT NULL
AND anyo NOT LIKE '%9%';

-- OTHER QUERIES

-- Exercise 55
SELECT cod_gen, nombre
FROM cs_genero LEFT JOIN cs_clasificacion USING (cod_gen)
WHERE cod_peli IN (
    SELECT cod_peli
    FROM cs_pelicula
    WHERE duracion = (
        SELECT MAX(duracion)
        FROM cs_pelicula
    )
);

-- Exercise 56
SELECT cs_actor.cod_act, nombre, fecha_nac, COUNT(cod_peli) CUANTOS
FROM cs_actor
    LEFT JOIN cs_actua
    ON papel = 'Principal'
    AND cs_actor.cod_act = cs_actua.cod_act
WHERE cs_actor.cod_act IN (
    SELECT cod_act
    FROM cs_actor
    WHERE fecha_nac < '01/01/1948'
    AND cod_act IN (
        SELECT cod_act
        FROM cs_actua
        GROUP BY cod_act
        HAVING COUNT(DISTINCT cod_peli) >= 2
    )
) GROUP BY cs_actor.cod_act, nombre, fecha_nac
ORDER BY nombre;
