//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GestDepLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>Encoded as a bitmap using [Flags] attribute</remarks>
	[Flags]
	public enum Days : int
	{
		Monday = 1,
		Tuesday = 2,
		Sunday = 64,
		Wednesday = 4,
		Thursday = 8,
		Friday = 16,
		Saturday = 32,
	}
}
