//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GestDepLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Person
	{
		public string Id
		{
			get;
			set;
		}

		public string Address
		{
			get;
			set;
		}

		public string Name
		{
			get;
			set;
		}

		public int ZipCode
		{
			get;
			set;
		}

		public string IBAN
		{
			get;
			set;
		}

	}
}

