//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GestDepLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Enrollment
	{
		public DateTime EnrollmentDate
		{
			get;
			set;
		}

		public DateTime? CancellationDate
		{
			get;
			set;
		}

		public int Id
		{
			get;
			set;
		}

		public DateTime? ReturnedFirstCuotaIfCancelledCourse
		{
			get;
			set;
		}

		public virtual ICollection<Payment> Payments
		{
			get;
			set;
		}

		public virtual User User
		{
			get;
			set;
		}

		public virtual Course Course
		{
			get;
			set;
		}

	}
}

