//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace GestDepLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Pool
	{
		public DateTime OpeningHour
		{
			get;
			set;
		}

		public DateTime ClosingHour
		{
			get;
			set;
		}

		public int ZipCode
		{
			get;
			set;
		}

		public int Id
		{
			get;
			set;
		}

		public int DiscountRetired
		{
			get;
			set;
		}

		public int DiscountLocal
		{
			get;
			set;
		}

		public double FreeSwimPrice
		{
			get;
			set;
		}

		public virtual ICollection<Lane> Lanes
		{
			get;
			set;
		}

	}
}

