//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ISWVehicleRentalExampleLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class CreditCard
	{
		public string digitsCC
		{
			get;
			set;
		}

		public int monthCC
		{
			get;
			set;
		}

		public int yearCC
		{
			get;
			set;
		}

		public int cvcCC
		{
			get;
			set;
		}

		public string typeCC
		{
			get;
			set;
		}

	}
}

