//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ISWVehicleRentalExampleLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Reservation
	{
		public DateTime pickupDate
		{
			get;
			set;
		}

		public DateTime returnDate
		{
			get;
			set;
		}

		public int Id
		{
			get;
			set;
		}

		public virtual Category Category
		{
			get;
			set;
		}

		public virtual BranchOffice PickupBranchOffice
		{
			get;
			set;
		}

		public virtual BranchOffice ReturnBranchOffice
		{
			get;
			set;
		}

		public virtual ICollection<Person> Drivers
		{
			get;
			set;
		}

		public virtual Customer Customer
		{
			get;
			set;
		}

	}
}

